### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by sneham9**
minor fix

### CODE REVIEW

**Comment by sneham9** [comment]
@gombrowicz94 
Thanks for your comments to the previous review request! Since we had to close that pull request, I'll address them here:
1. Users don't need to be exposed to some of the functions in the base class. I will change them to private and add a new update to this pull request.
2. The shape of x and y inputs and scaling required are slightly different based on the model we are using. _model() is doing this transformation and calling the correct model based on the class.  It's similar for AR and regularised regression models but different for neural networks. Since we are not repeating the code more than twice, I did not make it into a function. Let me know what you think!
3. I think sklearn is better than glmnet because its a more common dependency and easy to install and work with than glmnet.

**Comment by sneham9** [comment]
1. changing some functions to private, thanks for the comment @gombrowicz94 
2. option to include PCA features  to run regression models, and AR+PCR model
3. Improving unittests

**Review by arorap95 — APPROVED** [review]
Looks good now! Thanks for the changes

**Review by gombrowicz94 — APPROVED** [review]
Great work! Thanks for making those changes.

**Pull request merged**
