### PR TITLE
Fix bug and submit for code review

### PR DESCRIPTION
**Pull request by arorap95**
Fixing a bug in the return calculation and submitting for code review

### CODE REVIEW

**Review by sneham9 — COMMENTED** [review]
Looks good! I have a suggestion for a performance improvement - there are loops across time and across assets. Let's see if we can vectorize some of these?

**Review by sneham9 — CHANGES_REQUESTED** [review]
Looks good! I have a suggestion for a performance improvement - there are loops across time and across assets. Let's see if we can vectorize some of these?

**Comment by arorap95** [comment]
> Looks good! I have a suggestion for a performance improvement - there are loops across time and across assets. Let's see if we can vectorize some of these?

I have made the vectorization changes so the code is now running faster. Resubmitting for your review

**Review by sneham9 — APPROVED** [review]
looks good!

**Pull request merged**
